package com.yt.ui.screens.player.state

import com.google.common.truth.Truth.assertThat
import com.yt.player.state.SubtitleOption
import org.junit.Test

/**
 * Only [SubtitleSelection.indexOfLanguage] is pure; `applyAt`, `enable` and `disable` reach the
 * player singleton and are exercised on a device. These pin how a remembered language tag is
 * resolved against the tracks a video actually offers.
 */
class SubtitleSelectionTest {
    private fun option(
        language: String,
        auto: Boolean = false,
        translated: Boolean = false,
    ) = SubtitleOption(
        url = "https://example.invalid/$language",
        language = language,
        label = language,
        isAutoGenerated = auto,
        isTranslated = translated,
    )

    @Test
    fun `an exact tag match returns its index`() {
        val subtitles = listOf(option("fr"), option("en"), option("de"))

        assertThat(SubtitleSelection.indexOfLanguage(subtitles, "en")).isEqualTo(1)
        assertThat(SubtitleSelection.indexOfLanguage(subtitles, "de")).isEqualTo(2)
    }

    @Test
    fun `the match is case insensitive and tolerates underscores`() {
        val subtitles = listOf(option("fr"), option("en-US"))

        assertThat(SubtitleSelection.indexOfLanguage(subtitles, "EN-us")).isEqualTo(1)
        assertThat(SubtitleSelection.indexOfLanguage(subtitles, "en_GB")).isEqualTo(1)
    }

    @Test
    fun `a regional tag falls back to the base language`() {
        val subtitles = listOf(option("fr"), option("en"))

        assertThat(SubtitleSelection.indexOfLanguage(subtitles, "en-US")).isEqualTo(1)
        assertThat(SubtitleSelection.indexOfLanguage(subtitles, "fr-CA")).isEqualTo(0)
    }

    @Test
    fun `an exact regional match beats a base language match`() {
        val subtitles = listOf(option("en"), option("en-GB"), option("en-US"))

        assertThat(SubtitleSelection.indexOfLanguage(subtitles, "en-US")).isEqualTo(2)
        assertThat(SubtitleSelection.indexOfLanguage(subtitles, "en-GB")).isEqualTo(1)
    }

    @Test
    fun `a human authored track beats an auto generated one for the same language`() {
        val subtitles = listOf(option("en", auto = true), option("en"))

        assertThat(SubtitleSelection.indexOfLanguage(subtitles, "en")).isEqualTo(1)
    }

    @Test
    fun `a machine translated track counts as auto generated`() {
        val subtitles = listOf(option("en", translated = true), option("en"))

        assertThat(SubtitleSelection.indexOfLanguage(subtitles, "en")).isEqualTo(1)
    }

    @Test
    fun `exactness outranks authorship`() {
        // Pins current behaviour: the tag comparison is the primary key, so an auto-generated exact
        // regional match wins over a human-authored base-language track.
        val subtitles = listOf(option("en-US", auto = true), option("en"))

        assertThat(SubtitleSelection.indexOfLanguage(subtitles, "en-US")).isEqualTo(0)
        assertThat(SubtitleSelection.indexOfLanguage(subtitles, "en")).isEqualTo(1)
    }

    @Test
    fun `the first of two equally ranked tracks wins`() {
        val subtitles = listOf(option("en", auto = true), option("en", auto = true))

        assertThat(SubtitleSelection.indexOfLanguage(subtitles, "en")).isEqualTo(0)
    }

    @Test
    fun `no match is minus one`() {
        val subtitles = listOf(option("fr"), option("de"))

        assertThat(SubtitleSelection.indexOfLanguage(subtitles, "en")).isEqualTo(-1)
        assertThat(SubtitleSelection.indexOfLanguage(emptyList(), "en")).isEqualTo(-1)
    }

    @Test
    fun `no remembered language is minus one`() {
        val subtitles = listOf(option("en"))

        assertThat(SubtitleSelection.indexOfLanguage(subtitles, null)).isEqualTo(-1)
        assertThat(SubtitleSelection.indexOfLanguage(subtitles, "")).isEqualTo(-1)
        assertThat(SubtitleSelection.indexOfLanguage(subtitles, "   ")).isEqualTo(-1)
        assertThat(SubtitleSelection.indexOfLanguage(subtitles, "none")).isEqualTo(-1)
    }
}
