package com.yt.player.stream

import android.util.Log
import com.yt.innertube.models.response.PlayerResponse
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import java.util.Locale

object CaptionTrackResolver {
    private const val TAG = "CaptionTrackResolver"

    /** Marks a track produced by YouTube's machine translation of another caption track. */
    const val TRANSLATED_PARAM = "tlang"

    const val NO_PREFERRED_LANGUAGE = "none"

    /**
     * @param format timedtext format requested for authored tracks. Defaults to
     *   [MediaFormat.TRANSCRIPT3] (srv3), YouTube's own styled/positioned caption XML, decoded by
     *   [com.yt.player.renderer.subtitle.Srv3SubtitleParser]. Callers that need the
     *   plain-text `vtt` conversion (offline downloads validate and store the raw response body)
     *   pass [MediaFormat.VTT] explicitly. Auto-generated (ASR) tracks always stay on `vtt`
     *   regardless: their srv3 form is a roll-up stream of word-timed segments, which the rolling
     *   caption renderer does not reconstruct.
     */
    fun resolve(
        playerResponse: PlayerResponse,
        format: MediaFormat = MediaFormat.TRANSCRIPT3,
    ): List<SubtitlesStream> = resolveTracklist(playerResponse.captions?.playerCaptionsTracklistRenderer, format)

    fun resolveTracklist(
        renderer: PlayerResponse.Captions.PlayerCaptionsTracklistRenderer?,
        format: MediaFormat = MediaFormat.TRANSCRIPT3,
    ): List<SubtitlesStream> {
        if (renderer == null) return emptyList()
        val tracks =
            renderer.captionTracks
                ?.filter { !it.baseUrl.isNullOrBlank() && !it.languageCode.isNullOrBlank() }
                .orEmpty()
        if (tracks.isEmpty()) return emptyList()

        val result =
            tracks.mapNotNull { track ->
                val autoGenerated = track.kind == "asr"
                buildStream(
                    track.baseUrl!!,
                    track.languageCode!!,
                    autoGenerated = autoGenerated,
                    format = if (autoGenerated) MediaFormat.VTT else format,
                )
            }

        Log.d(TAG, "Resolved ${result.size} caption tracks from InnerTube captions")
        return result
    }

    fun isTranslated(stream: SubtitlesStream): Boolean = stream.getContent().contains("&$TRANSLATED_PARAM=")

    private fun buildStream(
        baseUrl: String,
        languageCode: String,
        autoGenerated: Boolean,
        format: MediaFormat,
    ): SubtitlesStream? =
        try {
            SubtitlesStream
                .Builder()
                .setContent(timedTextUrl(baseUrl, format), true)
                .setMediaFormat(format)
                .setLanguageCode(languageCode)
                .setAutoGenerated(autoGenerated)
                .build()
        } catch (e: Exception) {
            Log.w(TAG, "Failed to build SubtitlesStream for $languageCode: ${e.message}")
            null
        }

    private fun timedTextUrl(
        baseUrl: String,
        format: MediaFormat,
    ): String {
        val separatorIndex = baseUrl.indexOf('?')
        val path = if (separatorIndex >= 0) baseUrl.substring(0, separatorIndex) else baseUrl
        val query = if (separatorIndex >= 0) baseUrl.substring(separatorIndex + 1) else ""

        val retained =
            query
                .split('&')
                .filter { it.isNotEmpty() && !it.isParam("fmt") && !it.isParam(TRANSLATED_PARAM) }
                .toMutableList()

        retained.add("fmt=${format.fmtQueryValue()}")

        return "$path?${retained.joinToString("&")}"
    }

    private fun MediaFormat.fmtQueryValue(): String =
        when (this) {
            MediaFormat.TRANSCRIPT3 -> "srv3"
            MediaFormat.VTT -> "vtt"
            else -> throw IllegalArgumentException("Unsupported timedtext format: $this")
        }

    private fun String.isParam(name: String): Boolean = startsWith("$name=", ignoreCase = true) || equals(name, ignoreCase = true)

    fun <T> bestMatch(
        candidates: List<T>,
        languageTag: String?,
        tagOf: (T) -> String?,
        isAutoGenerated: (T) -> Boolean,
    ): T? {
        val wanted = languageTag?.takeIf { it.isNotBlank() && it != NO_PREFERRED_LANGUAGE } ?: return null
        val wantedBase = baseLanguage(wanted)
        val ranked =
            candidates
                .filter { baseLanguage(tagOf(it).orEmpty()) == wantedBase }
                .sortedWith(
                    compareBy<T> { !tagOf(it).equals(wanted, ignoreCase = true) }
                        .thenBy { isAutoGenerated(it) },
                )
        return ranked.firstOrNull()
    }

    private fun baseLanguage(tag: String): String =
        tag
            .substringBefore('-')
            .substringBefore('_')
            .lowercase(Locale.ROOT)
}
