package com.yt.player.stream

import android.util.Log
import com.yt.player.state.AudioTrackOption
import com.yt.player.state.SubtitleOption
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.AudioTrackType
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.extractor.stream.VideoStream
import java.util.Locale

/**
 * Manages stream data processing - deduplication, sorting, and conversion.
 */
object StreamProcessor {
    private const val TAG = "StreamProcessor"

    /** Grouping key for audio carrying no track identity at all. */
    internal const val UNTAGGED_TRACK_KEY = "default"

    /**
     * Process video streams - deduplicate and sort by height descending.
     */
    fun processVideoStreams(streams: List<VideoStream>): List<VideoStream> =
        streams
            .distinctBy { it.getContent() }
            .sortedWith(
                compareByDescending<VideoStream> { VideoCodecUtils.qualityHeightFromStream(it) }
                    .thenBy { VideoCodecUtils.playbackCodecRank(it) }
                    .thenByDescending { it.bitrate },
            ).also { Log.d(TAG, "Processed ${streams.size} video streams -> ${it.size} unique") }

    fun processAudioStreams(streams: List<AudioStream>): List<AudioStream> =
        streams
            .sortedByDescending { it.averageBitrate }
            .groupBy { stream -> extractTrackLanguageKey(stream) }
            .dropUntaggedGroupWhenTracksAreKnown()
            .map { (_, group) ->
                group.first()
            }.sortedBy { stream -> audioTrackDisplayName(stream).orEmpty() }
            .also { Log.d(TAG, "Processed ${streams.size} audio streams -> ${it.size} unique tracks") }

    /**
     * Once named tracks are present, the untagged bucket is the same audio arriving from a backend
     * that does not name tracks (the two extraction paths get merged). Keeping it would render an
     * unlabelled duplicate row beside the real ones.
     */
    private fun Map<String, List<AudioStream>>.dropUntaggedGroupWhenTracksAreKnown(): Map<String, List<AudioStream>> =
        if (size > 1) this - UNTAGGED_TRACK_KEY else this

    fun processSubtitleStreams(streams: List<SubtitlesStream>): List<SubtitlesStream> =
        streams
            .filter { it.getContent().isNotBlank() }
            .sortedBy { it.format != MediaFormat.VTT }
            .distinctBy { stream ->
                val lang = stream.languageTag ?: stream.locale?.toLanguageTag() ?: stream.getContent()
                "$lang|${stream.isAutoGenerated}|${CaptionTrackResolver.isTranslated(stream)}"
            }.sortedWith(
                compareBy<SubtitlesStream> { CaptionTrackResolver.isTranslated(it) }
                    .thenBy { it.isAutoGenerated }
                    .thenBy { it.displayLanguageName ?: it.languageTag ?: "" },
            ).also { Log.d(TAG, "Processed ${streams.size} subtitle streams -> ${it.size} unique tracks") }

    /**
     * Index of [stream]'s logical track within [tracks], or 0 when it cannot be placed.
     *
     * Matched by track identity rather than instance: the playing stream is picked from the raw
     * list while [tracks] holds one representative per track, so the two are rarely the same
     * object and an instance lookup silently reports the wrong row as selected.
     */
    fun indexOfAudioTrack(
        tracks: List<AudioStream>,
        stream: AudioStream?,
    ): Int {
        if (stream == null) return 0
        val key = extractTrackLanguageKey(stream)
        return tracks.indexOfFirst { extractTrackLanguageKey(it) == key }.coerceAtLeast(0)
    }

    /**
     * True when this stream is a track chosen over YouTube's default. Neither YouTube's own DASH
     * manifest nor a SABR session can serve such a choice — both carry only the default track — so
     * playback has to fall through to a manifest generated from this specific stream.
     */
    fun overridesDefaultAudioTrack(stream: AudioStream?): Boolean {
        val type = stream?.audioTrackType ?: return false
        return type != AudioTrackType.ORIGINAL
    }

    /** Derive a stable logical-track key while collapsing only alternate formats of that track. */
    private fun extractTrackLanguageKey(stream: AudioStream): String =
        audioTrackGroupingKey(
            trackId = stream.audioTrackId,
            trackName = stream.audioTrackName,
            languageTag = stream.audioLocale?.toLanguageTag(),
            trackType = stream.audioTrackType?.name,
        )

    /**
     * Derive a human-readable language display name from an AudioStream.
     * Priority: audioTrackName → audioLocale display language → parsed audioTrackId → fallback.
     */
    fun audioTrackDisplayName(stream: AudioStream): String? {
        stream.audioTrackName?.takeIf { it.isNotBlank() }?.let { return it }

        stream.audioLocale?.language?.takeIf { it.isNotBlank() }?.let { langCode ->
            localizedLanguageName(langCode)?.let { return it }
        }

        stream.audioTrackId?.let { trackId ->
            audioTrackLanguageTag(trackId)?.let { languageTag ->
                localizedLanguageName(languageTag)?.let { return it }
            }
            return trackId.replaceFirstChar { it.uppercase() }
        }

        return null
    }

    /**
     * Convert audio streams to UI options.
     */
    fun toAudioTrackOptions(streams: List<AudioStream>): List<AudioTrackOption> =
        streams.mapIndexed { index, stream ->
            AudioTrackOption(
                index = index,
                label = audioTrackDisplayName(stream).orEmpty(),
                language =
                    stream.audioLocale
                        ?.displayLanguage
                        ?.takeIf { it.isNotBlank() }
                        ?: "",
                bitrate = stream.averageBitrate.coerceAtLeast(0).toLong(),
            )
        }

    /**
     * Convert subtitle streams to UI options.
     */
    fun toSubtitleOptions(subtitles: List<SubtitlesStream>): List<SubtitleOption> =
        subtitles.map {
            val language = it.languageTag ?: it.locale?.toLanguageTag() ?: "Unknown"
            val baseLabel =
                localizedLanguageName(language)
                    ?: it.displayLanguageName
                    ?: language
            val isTranslated = CaptionTrackResolver.isTranslated(it)
            SubtitleOption(
                url = it.getContent(),
                language = language,
                label = baseLabel,
                isAutoGenerated = it.isAutoGenerated,
                isTranslated = isTranslated,
            )
        }

    private fun localizedLanguageName(languageTag: String): String? {
        val languageLocale = Locale.forLanguageTag(languageTag.replace('_', '-'))
        val languageCode = languageLocale.language.takeIf { it.isNotBlank() } ?: return null
        val displayLocale = Locale.getDefault()
        val displayName = languageLocale.getDisplayLanguage(displayLocale)
        if (displayName.isBlank() || displayName.equals(languageCode, ignoreCase = true)) return null
        return displayName.replaceFirstChar { character ->
            if (character.isLowerCase()) character.titlecase(displayLocale) else character.toString()
        }
    }

    internal fun audioTrackLanguageTag(trackId: String): String? {
        val normalized = trackId.trim()
        if (normalized.isEmpty()) return null

        val withoutRoleSuffix = normalized.substringBeforeLast('.', missingDelimiterValue = "")
        if (withoutRoleSuffix.isNotBlank()) return withoutRoleSuffix

        if (normalized.startsWith("A_")) {
            return normalized.substringAfterLast('_').takeIf { it.isNotBlank() }
        }

        return normalized.replace('_', '-').takeIf {
            Locale.forLanguageTag(it.replace('_', '-')).language.isNotBlank()
        }
    }

    internal fun audioTrackGroupingKey(
        trackId: String?,
        trackName: String?,
        languageTag: String?,
        trackType: String?,
    ): String {
        val type = trackType.orEmpty().lowercase(Locale.ROOT)
        trackId
            ?.trim()
            ?.takeIf { it.isNotEmpty() }
            ?.let { return "id:${it.lowercase(Locale.ROOT)}" }
        trackName
            ?.trim()
            ?.takeIf { it.isNotEmpty() }
            ?.let { return "name:${it.lowercase(Locale.ROOT)}|$type" }
        languageTag
            ?.trim()
            ?.takeIf { it.isNotEmpty() }
            ?.let { return "language:${it.lowercase(Locale.ROOT)}|$type" }
        return UNTAGGED_TRACK_KEY
    }
}
