package com.yt.player.stream

import com.yt.innertube.models.response.PlayerResponse
import com.yt.player.state.SubtitleOption
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.schabi.newpipe.extractor.MediaFormat

/** A signed timedtext URL as YouTube serves it today — note the trailing `fmt=srv3`. */
private const val BASE_URL =
    "https://www.youtube.com/api/timedtext?v=abc&ei=XYZ&caps=asr&sparams=ip,ipbits,expire,v" +
        "&signature=DEADBEEF.0123&key=yt8&lang=en&fmt=srv3"

private fun tracklist(tracks: List<PlayerResponse.Captions.CaptionTrack>) =
    PlayerResponse.Captions.PlayerCaptionsTracklistRenderer(captionTracks = tracks)

private fun track(
    languageCode: String,
    kind: String? = null,
    baseUrl: String = BASE_URL,
) = PlayerResponse.Captions.CaptionTrack(
    baseUrl = baseUrl,
    languageCode = languageCode,
    kind = kind,
)

class CaptionTrackResolverTest {
    @Test
    fun `srv3 is requested by default for styled and positioned captions`() {
        val resolved = CaptionTrackResolver.resolveTracklist(tracklist(listOf(track("en"))))

        val url = resolved.single().getContent()
        assertEquals("exactly one fmt parameter expected: $url", 1, url.split("fmt=").size - 1)
        assertTrue(url.endsWith("fmt=srv3"))
    }

    @Test
    fun `an explicit vtt format request is honoured, not duplicated`() {
        val resolved =
            CaptionTrackResolver.resolveTracklist(tracklist(listOf(track("en"))), format = MediaFormat.VTT)

        val url = resolved.single().getContent()
        assertFalse("srv3 must not survive: $url", url.contains("fmt=srv3"))
        assertEquals("exactly one fmt parameter expected: $url", 1, url.split("fmt=").size - 1)
        assertTrue(url.endsWith("fmt=vtt"))
    }

    @Test
    fun `signed parameters survive untouched so the url stays valid`() {
        val url = CaptionTrackResolver.resolveTracklist(tracklist(listOf(track("en")))).single().getContent()

        assertTrue(url.contains("signature=DEADBEEF.0123"))
        assertTrue("commas in sparams must not be re-encoded: $url", url.contains("sparams=ip,ipbits,expire,v"))
        assertTrue(url.startsWith("https://www.youtube.com/api/timedtext?"))
    }

    @Test
    fun `machine translations are not offered`() {
        // YouTube throttles timedtext requests carrying &tlang= hard enough that the tracks are
        // dead more often than not, so the menu must not advertise them at all.
        val resolved = CaptionTrackResolver.resolveTracklist(tracklist(listOf(track("en"), track("de-DE"))))

        assertEquals(listOf("en", "de-DE"), resolved.map { it.languageTag })
        assertTrue(resolved.none { CaptionTrackResolver.isTranslated(it) })
        assertTrue("no tlang may reach the player: ${resolved.map { it.getContent() }}", resolved.none { "tlang" in it.getContent() })
    }

    @Test
    fun `an auto generated caption track is still marked as such`() {
        val resolved = CaptionTrackResolver.resolveTracklist(tracklist(listOf(track("en", kind = "asr"))))

        assertTrue(resolved.single().isAutoGenerated)
    }

    @Test
    fun `auto generated tracks stay on vtt even when srv3 is the default`() {
        // YouTube serves ASR srv3 as a roll-up of word-timed segments; the rolling caption bubble
        // rebuilds the current line from plain cues and cannot read that structure.
        val resolved =
            CaptionTrackResolver.resolveTracklist(tracklist(listOf(track("en"), track("en", kind = "asr"))))

        val authored = resolved.single { !it.isAutoGenerated }
        val auto = resolved.single { it.isAutoGenerated }

        assertEquals(MediaFormat.TRANSCRIPT3, authored.format)
        assertTrue(authored.getContent().endsWith("fmt=srv3"))
        assertEquals(MediaFormat.VTT, auto.format)
        assertTrue("ASR must not be requested as srv3: ${auto.getContent()}", auto.getContent().endsWith("fmt=vtt"))
    }

    @Test
    fun `a stored region tag still matches the base language and prefers the human track`() {
        val options =
            listOf(
                SubtitleOption(url = "a", language = "pt-BR", label = "Portuguese", isAutoGenerated = true),
                SubtitleOption(url = "b", language = "pt-BR", label = "Portuguese", isAutoGenerated = false),
                SubtitleOption(url = "c", language = "en", label = "English", isAutoGenerated = false),
            )

        val match =
            CaptionTrackResolver.bestMatch(
                candidates = options,
                languageTag = "pt",
                tagOf = { it.language },
                isAutoGenerated = { it.isAutoGenerated },
            )

        assertEquals("b", match?.url)
    }

    @Test
    fun `no preference matches nothing`() {
        val options = listOf(SubtitleOption(url = "a", language = "en", label = "English", isAutoGenerated = false))

        assertNull(
            CaptionTrackResolver.bestMatch(
                candidates = options,
                languageTag = CaptionTrackResolver.NO_PREFERRED_LANGUAGE,
                tagOf = { it.language },
                isAutoGenerated = { it.isAutoGenerated },
            ),
        )
    }
}
