package com.yt.ui.components.videoplayer.subtitle

import android.graphics.Typeface
import android.util.TypedValue
import android.view.ViewGroup
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.fadeIn
import androidx.compose.animation.fadeOut
import androidx.compose.animation.slideInVertically
import androidx.compose.animation.slideOutVertically
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.media3.common.Player
import androidx.media3.common.text.Cue
import androidx.media3.common.text.CueGroup
import androidx.media3.ui.CaptionStyleCompat
import androidx.media3.ui.SubtitleView
import com.yt.player.EnhancedPlayerManager
import android.graphics.Color as AndroidColor

@Composable
fun Media3SubtitleOverlay(
    enabled: Boolean,
    isAutoGenerated: Boolean,
    style: SubtitleStyle = SubtitleStyle(),
    modifier: Modifier = Modifier,
) {
    var cues by remember { mutableStateOf(emptyList<Cue>()) }
    val player = EnhancedPlayerManager.getInstance().getPlayer()

    DisposableEffect(player) {
        if (player == null) {
            onDispose { }
        } else {
            val listener =
                object : Player.Listener {
                    override fun onCues(cueGroup: CueGroup) {
                        cues = cueGroup.cues
                    }
                }
            player.addListener(listener)
            cues = player.currentCues.cues
            onDispose {
                player.removeListener(listener)
            }
        }
    }

    if (!enabled) return

    // Auto-generated (ASR) captions arrive as a rolling window of overlapping, growing cues and
    // are always plain text, so they keep the dedicated bubble that reconstructs the latest line.
    // Authored/uploaded tracks (and srv3 in particular) carry real multiline text, per-run
    // styling and window position, so they're handed to Media3's own SubtitleView, which is the
    // one renderer in this app that actually honours a Cue's spans and placement.
    if (isAutoGenerated) {
        RollingCaptionBubble(cues = cues, style = style, modifier = modifier)
    } else {
        StyledSubtitleView(cues = cues, style = style, modifier = modifier)
    }
}

@Composable
private fun RollingCaptionBubble(
    cues: List<Cue>,
    style: SubtitleStyle,
    modifier: Modifier,
) {
    val displayText = remember(cues) { cues.toRollingCaptionText() }
    val bottomPadding = style.bottomPadding.coerceIn(24f, 220f)

    AnimatedVisibility(
        visible = displayText != null,
        enter = fadeIn() + slideInVertically { it / 2 },
        exit = fadeOut() + slideOutVertically { it / 2 },
        modifier = modifier.fillMaxSize(),
    ) {
        if (displayText != null) {
            Box(
                modifier =
                    Modifier
                        .fillMaxSize()
                        .padding(horizontal = 16.dp),
                contentAlignment = Alignment.BottomCenter,
            ) {
                Surface(
                    color = style.backgroundColor,
                    shape = RoundedCornerShape(8.dp),
                    modifier = Modifier.offset(y = -bottomPadding.dp),
                ) {
                    Text(
                        text = displayText,
                        color = style.textColor,
                        fontSize = style.fontSize.sp,
                        fontWeight = if (style.isBold) FontWeight.Bold else FontWeight.Normal,
                        textAlign = TextAlign.Center,
                        lineHeight = (style.fontSize * 1.25f).sp,
                        modifier = Modifier.padding(horizontal = 12.dp, vertical = 6.dp),
                    )
                }
            }
        }
    }
}

@Composable
private fun StyledSubtitleView(
    cues: List<Cue>,
    style: SubtitleStyle,
    modifier: Modifier,
) {
    val visibleCues = remember(cues) { cues.filter { !it.text.isNullOrBlank() } }

    // Deliberately not wrapped in AnimatedVisibility: cues empty out in the gap between every
    // caption, which would tear the SubtitleView down and re-inflate it hundreds of times per
    // video. An empty cue list already draws nothing.
    BoxWithConstraints(modifier = modifier.fillMaxSize()) {
        val bottomPaddingFraction =
            if (maxHeight.value > 0f) {
                (style.bottomPadding / maxHeight.value).coerceIn(0.02f, 0.4f)
            } else {
                SubtitleView.DEFAULT_BOTTOM_PADDING_FRACTION
            }
        val captionStyle =
            remember(style) {
                CaptionStyleCompat(
                    style.textColor.toArgb(),
                    style.backgroundColor.toArgb(),
                    AndroidColor.TRANSPARENT,
                    CaptionStyleCompat.EDGE_TYPE_NONE,
                    AndroidColor.TRANSPARENT,
                    if (style.isBold) Typeface.DEFAULT_BOLD else Typeface.DEFAULT,
                )
            }

        AndroidView(
            modifier =
                Modifier
                    .fillMaxSize()
                    .padding(horizontal = 16.dp),
            factory = { context ->
                SubtitleView(context).apply {
                    setApplyEmbeddedStyles(true)
                    setApplyEmbeddedFontSizes(false)
                }
            },
            update = { view ->
                view.setBottomPaddingFraction(bottomPaddingFraction)
                view.setFixedTextSize(TypedValue.COMPLEX_UNIT_SP, style.fontSize)
                view.setStyle(captionStyle)
                view.setCues(visibleCues)
            },
        )
    }
}

private fun List<Cue>.toRollingCaptionText(): String? {
    val textCues =
        mapNotNull { it.text?.toString()?.cleanRollingCueText() }
            .filter { it.isNotBlank() }
            .distinct()

    if (textCues.isEmpty()) return null

    return when (textCues.size) {
        1 -> textCues.first()
        else -> textCues.last()
    }.takeIf { it.isNotBlank() }
}

private fun String.cleanRollingCueText(): String {
    val lines =
        replace('\u00A0', ' ')
            .replace(Regex("[ \\t\\x0B\\f\\r]+"), " ")
            .lines()
            .map { it.trim() }
            .filter { it.isNotBlank() }

    if (lines.isEmpty()) return ""

    return lines.latestRollingCaptionLine()
}

private fun List<String>.latestRollingCaptionLine(): String {
    if (size == 1) return first()

    val latestLine = last()
    val previousLine = this[size - 2]
    val previousWords = previousLine.splitWords()
    val latestWords = latestLine.splitWords()

    if (previousWords.isEmpty() || latestWords.isEmpty()) return latestLine

    val overlap = longestSuffixPrefixOverlap(previousWords, latestWords)
    val freshWords = latestWords.drop(overlap)

    return freshWords
        .takeIf { it.isNotEmpty() }
        ?.joinToString(" ")
        ?: latestLine
}

private fun String.splitWords(): List<String> = split(Regex("\\s+")).filter { it.isNotBlank() }

private fun longestSuffixPrefixOverlap(
    previous: List<String>,
    latest: List<String>,
): Int {
    val maxOverlap = minOf(previous.size, latest.size)
    for (count in maxOverlap downTo 1) {
        val previousSuffix = previous.takeLast(count)
        val latestPrefix = latest.take(count)
        if (previousSuffix.equalsWords(latestPrefix)) {
            return count
        }
    }
    return 0
}

private fun List<String>.equalsWords(other: List<String>): Boolean {
    if (size != other.size) return false
    return indices.all { index ->
        this[index].trimPunctuation().equals(other[index].trimPunctuation(), ignoreCase = true)
    }
}

private fun String.trimPunctuation(): String = trim { !it.isLetterOrDigit() }
