package com.yt.data.video

import android.content.Context
import android.util.Log
import dagger.hilt.android.qualifiers.ApplicationContext
import com.yt.innertube.YouTube
import com.yt.innertube.models.YouTubeClient
import com.yt.player.stream.CaptionTrackResolver
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import org.json.JSONArray
import org.json.JSONObject
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import java.io.File
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Keeps a downloaded video's caption tracks on disk beside the download.
 *
 * Caption URLs are signed and expire within hours, so a download that only remembers the URL has
 * no captions the next time the app starts. The tracks themselves are a few KB of text, so they
 * are fetched once at download time and replayed from local files afterwards — which also makes
 * captions work with no network at all.
 */
@Singleton
class OfflineSubtitleStore
    @Inject
    constructor(
        @ApplicationContext private val context: Context,
        private val httpClient: OkHttpClient,
    ) {
        private val rootDir: File
            get() = File(context.filesDir, ROOT_DIR)

        private fun videoDir(videoId: String) = File(rootDir, videoId.sanitized())

        /**
         * Resolve and store the video's native caption tracks. Auto-translations are skipped: they
         * are derived from a track we already keep and would multiply the stored files by twenty.
         */
        suspend fun saveForVideo(videoId: String): Int =
            withContext(Dispatchers.IO) {
                try {
                    val streams = resolveCaptionTracks(videoId)
                    if (streams.isEmpty()) {
                        Log.d(TAG, "No caption tracks to store for $videoId")
                        return@withContext 0
                    }
                    save(videoId, streams)
                } catch (e: Exception) {
                    Log.w(TAG, "Storing captions for $videoId failed: ${e.message}")
                    0
                }
            }

        suspend fun save(
            videoId: String,
            streams: List<SubtitlesStream>,
        ): Int =
            withContext(Dispatchers.IO) {
                val dir = videoDir(videoId)
                if (!dir.exists() && !dir.mkdirs()) {
                    Log.w(TAG, "Could not create caption dir for $videoId")
                    return@withContext 0
                }

                val stored = JSONArray()
                streams
                    .filterNot { CaptionTrackResolver.isTranslated(it) }
                    .forEach { stream ->
                        val languageTag = stream.languageTag ?: stream.locale?.toLanguageTag() ?: return@forEach
                        val fileName = captionFileName(languageTag, stream.isAutoGenerated)
                        val target = File(dir, fileName)
                        if (!downloadTo(stream.getContent(), target)) return@forEach
                        stored.put(
                            JSONObject().apply {
                                put(KEY_LANGUAGE, languageTag)
                                put(KEY_AUTO_GENERATED, stream.isAutoGenerated)
                                put(KEY_FILE, fileName)
                            },
                        )
                    }

                if (stored.length() == 0) {
                    dir.deleteRecursively()
                    return@withContext 0
                }

                File(dir, INDEX_FILE).writeText(JSONObject().put(KEY_TRACKS, stored).toString())
                Log.d(TAG, "Stored ${stored.length()} offline caption track(s) for $videoId")
                stored.length()
            }

        /** Caption tracks previously stored for [videoId], as file-backed streams. */
        suspend fun load(videoId: String): List<SubtitlesStream> =
            withContext(Dispatchers.IO) {
                val dir = videoDir(videoId)
                val index = File(dir, INDEX_FILE)
                if (!index.isFile) return@withContext emptyList()

                try {
                    val tracks = JSONObject(index.readText()).optJSONArray(KEY_TRACKS) ?: return@withContext emptyList()
                    (0 until tracks.length()).mapNotNull { position ->
                        val entry = tracks.optJSONObject(position) ?: return@mapNotNull null
                        val file = File(dir, entry.optString(KEY_FILE))
                        if (!file.isFile) return@mapNotNull null
                        runCatching {
                            SubtitlesStream
                                .Builder()
                                .setContent(file.toURI().toString(), true)
                                .setMediaFormat(MediaFormat.VTT)
                                .setLanguageCode(entry.optString(KEY_LANGUAGE))
                                .setAutoGenerated(entry.optBoolean(KEY_AUTO_GENERATED))
                                .build()
                        }.getOrNull()
                    }
                } catch (e: Exception) {
                    Log.w(TAG, "Reading offline captions for $videoId failed: ${e.message}")
                    emptyList()
                }
            }

        suspend fun delete(videoId: String) =
            withContext(Dispatchers.IO) {
                videoDir(videoId).deleteRecursively()
                Unit
            }

        private suspend fun resolveCaptionTracks(videoId: String): List<SubtitlesStream> {
            CAPTION_CLIENTS.forEach { client ->
                val response = YouTube.player(videoId, client = client).getOrNull()
                // VTT, not the default srv3: downloadTo() below validates and stores the raw
                // WEBVTT body as-is, and offline playback only ever builds MediaFormat.VTT streams.
                val streams = response?.let { CaptionTrackResolver.resolve(it, format = MediaFormat.VTT) }.orEmpty()
                if (streams.isNotEmpty()) return streams
            }
            return emptyList()
        }

        private fun downloadTo(
            url: String,
            target: File,
        ): Boolean =
            try {
                httpClient
                    .newCall(Request.Builder().url(url).build())
                    .execute()
                    .use { response ->
                        val body = response.body?.string()
                        if (!response.isSuccessful || body.isNullOrBlank() || !body.startsWith(VTT_MAGIC)) {
                            Log.w(TAG, "Caption fetch rejected (${response.code}) for ${target.name}")
                            false
                        } else {
                            target.writeText(body)
                            true
                        }
                    }
            } catch (e: Exception) {
                Log.w(TAG, "Caption fetch failed for ${target.name}: ${e.message}")
                false
            }

        private fun captionFileName(
            languageTag: String,
            autoGenerated: Boolean,
        ): String = "${languageTag.sanitized()}${if (autoGenerated) ".auto" else ""}.vtt"

        private fun String.sanitized(): String = replace(Regex("[^A-Za-z0-9_.-]"), "_")

        companion object {
            private const val TAG = "OfflineSubtitleStore"
            private const val ROOT_DIR = "offline_subtitles"
            private const val INDEX_FILE = "index.json"
            private const val KEY_TRACKS = "tracks"
            private const val KEY_LANGUAGE = "language"
            private const val KEY_AUTO_GENERATED = "autoGenerated"
            private const val KEY_FILE = "file"
            private const val VTT_MAGIC = "WEBVTT"

            private val CAPTION_CLIENTS = listOf(YouTubeClient.ANDROID_VR_NO_AUTH, YouTubeClient.MOBILE)
        }
    }
