package com.yt.ui.screens.player.state

import com.yt.player.EnhancedPlayerManager
import com.yt.player.state.SubtitleOption
import com.yt.player.stream.CaptionTrackResolver

internal object SubtitleSelection {
    fun indexOfLanguage(
        subtitles: List<SubtitleOption>,
        languageTag: String?,
    ): Int {
        val match =
            CaptionTrackResolver.bestMatch(
                candidates = subtitles,
                languageTag = languageTag,
                tagOf = { it.language },
                isAutoGenerated = { it.isAutoGenerated || it.isTranslated },
            ) ?: return -1
        return subtitles.indexOf(match)
    }

    /** Index to fall back on when nothing is remembered: a human-authored track if there is one. */
    private fun defaultIndex(subtitles: List<SubtitleOption>): Int =
        subtitles
            .indexOfFirst { !it.isAutoGenerated && !it.isTranslated }
            .takeIf { it >= 0 }
            ?: subtitles.indices.firstOrNull() ?: -1

    fun applyAt(
        screenState: PlayerScreenState,
        subtitles: List<SubtitleOption>,
        index: Int,
        rememberLanguage: (String) -> Unit,
    ): Boolean {
        val subtitle = subtitles.getOrNull(index) ?: return false
        EnhancedPlayerManager.getInstance().selectSubtitle(index)
        screenState.enableSubtitles(subtitle.url)
        subtitle.language.takeIf { it.isNotBlank() }?.let(rememberLanguage)
        return true
    }

    fun enable(
        screenState: PlayerScreenState,
        subtitles: List<SubtitleOption>,
        languageTag: String?,
        rememberLanguage: (String) -> Unit,
    ): Boolean {
        if (subtitles.isEmpty()) return false
        val index = indexOfLanguage(subtitles, languageTag).takeIf { it >= 0 } ?: defaultIndex(subtitles)
        return applyAt(screenState, subtitles, index, rememberLanguage)
    }

    fun disable(screenState: PlayerScreenState) {
        EnhancedPlayerManager.getInstance().selectSubtitle(null)
        screenState.disableSubtitles()
    }
}
