package com.yt.ui.screens.player

import androidx.lifecycle.HasDefaultViewModelProviderFactory
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.ViewModelStore
import androidx.lifecycle.ViewModelStoreOwner
import androidx.lifecycle.viewmodel.CreationExtras
import com.yt.data.model.Comment
import com.yt.data.model.Video
import com.yt.innertube.models.response.PlayerResponse
import com.yt.player.state.AudioTrackOption
import com.yt.player.state.EnhancedPlayerState
import com.yt.player.state.QualityOption
import com.yt.player.state.SubtitleOption
import com.yt.ui.components.QuickActionsViewModel
import com.yt.ui.screens.player.state.VideoPlayerUiState
import io.mockk.every
import io.mockk.mockk
import io.mockk.mockkClass
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.flowOf

internal fun fakeVideo(
    id: String = "video-1",
    title: String = "Fixture video",
    channelName: String = "Fixture channel",
    channelId: String = "channel-1",
): Video =
    Video(
        id = id,
        title = title,
        channelName = channelName,
        channelId = channelId,
        thumbnailUrl = "",
        duration = 125,
        viewCount = 1_000L,
        uploadDate = "2026-01-01",
    )

internal val FIXTURE_QUALITY_AUTO = QualityOption(height = 0, label = "Auto", bitrate = 0L)
internal val FIXTURE_QUALITY_1080 =
    QualityOption(height = 1080, label = "1080p", bitrate = 5_000_000L, codecKey = "vp9", streamKey = "1080_vp9")
internal val FIXTURE_QUALITY_720 =
    QualityOption(height = 720, label = "720p", bitrate = 2_500_000L, codecKey = "h264", streamKey = "720_h264")

internal val FIXTURE_AUDIO_TRACKS =
    listOf(
        AudioTrackOption(index = 0, label = "English", language = "en", bitrate = 128_000L),
        AudioTrackOption(index = 1, label = "Deutsch", language = "de", bitrate = 128_000L),
    )

internal val FIXTURE_SUBTITLES =
    listOf(
        SubtitleOption(url = "https://example.invalid/en.vtt", language = "en", label = "English", isAutoGenerated = false),
    )

internal fun fakePlayerState(
    isPlaying: Boolean = false,
    isLive: Boolean = false,
    currentQuality: Int = 1080,
    effectiveQuality: Int = 1080,
    playbackSpeed: Float = 1.0f,
    availableQualities: List<QualityOption> = listOf(FIXTURE_QUALITY_AUTO, FIXTURE_QUALITY_1080, FIXTURE_QUALITY_720),
    availableAudioTracks: List<AudioTrackOption> = FIXTURE_AUDIO_TRACKS,
    availableSubtitles: List<SubtitleOption> = FIXTURE_SUBTITLES,
): EnhancedPlayerState =
    EnhancedPlayerState(
        currentVideoId = "video-1",
        isPlaying = isPlaying,
        isPrepared = true,
        currentQuality = currentQuality,
        effectiveQuality = effectiveQuality,
        currentQualityKey = FIXTURE_QUALITY_1080.streamKey,
        availableQualities = availableQualities,
        availableAudioTracks = availableAudioTracks,
        availableSubtitles = availableSubtitles,
        playbackSpeed = playbackSpeed,
        isLive = isLive,
    )

internal fun fakeUiState(
    video: Video = fakeVideo(),
    relatedVideos: List<Video> = emptyList(),
    isLiveChatAvailable: Boolean = false,
    innerTubeVideoFormats: List<PlayerResponse.StreamingData.Format> = emptyList(),
    innerTubeAudioFormats: List<PlayerResponse.StreamingData.Format> = emptyList(),
): VideoPlayerUiState =
    VideoPlayerUiState(
        cachedVideo = video,
        relatedVideos = relatedVideos,
        isLiveChatAvailable = isLiveChatAvailable,
        innerTubeVideoFormats = innerTubeVideoFormats,
        innerTubeAudioFormats = innerTubeAudioFormats,
    )

/** An InnerTube adaptive format with just enough metadata for [com.yt.player.stream.InnerTubeStreamBridge]. */
internal fun fakeInnerTubeFormat(
    itag: Int,
    mimeType: String,
    height: Int? = null,
    width: Int? = null,
    bitrate: Int = 1_000_000,
): PlayerResponse.StreamingData.Format =
    PlayerResponse.StreamingData.Format(
        itag = itag,
        url = "https://example.invalid/videoplayback?itag=$itag",
        mimeType = mimeType,
        bitrate = bitrate,
        width = width,
        height = height,
        contentLength = null,
        quality = "medium",
        fps = if (height != null) 30 else null,
        qualityLabel = height?.let { "${it}p" },
        averageBitrate = bitrate,
        audioQuality = if (height == null) "AUDIO_QUALITY_MEDIUM" else null,
        approxDurationMs = null,
        audioSampleRate = if (height == null) 44_100 else null,
        audioChannels = if (height == null) 2 else null,
        loudnessDb = null,
        lastModified = null,
        signatureCipher = null,
    )

internal fun fakeVideoFormats(): List<PlayerResponse.StreamingData.Format> =
    listOf(
        fakeInnerTubeFormat(itag = 137, mimeType = "video/mp4; codecs=\"avc1.640028\"", height = 1080, width = 1920, bitrate = 4_000_000),
        fakeInnerTubeFormat(itag = 248, mimeType = "video/webm; codecs=\"vp9\"", height = 1080, width = 1920, bitrate = 3_000_000),
        fakeInnerTubeFormat(itag = 136, mimeType = "video/mp4; codecs=\"avc1.4d401f\"", height = 720, width = 1280, bitrate = 2_000_000),
    )

internal fun fakeAudioFormats(): List<PlayerResponse.StreamingData.Format> =
    listOf(
        fakeInnerTubeFormat(itag = 140, mimeType = "audio/mp4; codecs=\"mp4a.40.2\"", bitrate = 128_000),
        fakeInnerTubeFormat(itag = 251, mimeType = "audio/webm; codecs=\"opus\"", bitrate = 160_000),
    )

/**
 * A relaxed [VideoPlayerViewModel] whose flows the player surfaces collect are real state flows, so
 * composables can subscribe without touching the Hilt graph the production ViewModel needs.
 */
internal fun relaxedVideoPlayerViewModel(
    uiState: MutableStateFlow<VideoPlayerUiState> = MutableStateFlow(fakeUiState()),
    comments: MutableStateFlow<List<Comment>> = MutableStateFlow(emptyList()),
): VideoPlayerViewModel {
    val viewModel = mockk<VideoPlayerViewModel>(relaxed = true)
    every { viewModel.uiState } returns uiState
    every { viewModel.commentsState } returns comments
    every { viewModel.isLoadingComments } returns MutableStateFlow(false)
    every { viewModel.hasMoreComments } returns MutableStateFlow(false)
    every { viewModel.isLoadingMoreComments } returns MutableStateFlow(false)
    every { viewModel.commentSortOptions } returns MutableStateFlow(emptyList())
    every { viewModel.commentTotalText } returns MutableStateFlow(null)
    every { viewModel.descriptionState } returns MutableStateFlow(null)
    every { viewModel.downloadedVideoIds } returns MutableStateFlow(emptySet())
    every { viewModel.videoNote } returns MutableStateFlow(null)
    every { viewModel.videoNotesEnabled } returns MutableStateFlow(false)
    every { viewModel.isVideoSavedToAnyPlaylist(any()) } returns flowOf(false)
    return viewModel
}

/**
 * Stands in for the Hilt-injected activity so `hiltViewModel()` inside video cards resolves to a
 * relaxed mock instead of trying to construct a real ViewModel through the default factory.
 */
internal class StubViewModelStoreOwner :
    ViewModelStoreOwner,
    HasDefaultViewModelProviderFactory {
    private val quickActions =
        mockk<QuickActionsViewModel>(relaxed = true).also {
            every { it.watchedVideoIds } returns MutableStateFlow(emptySet())
            every { it.subscribedChannelIds } returns MutableStateFlow(emptySet())
        }

    override val viewModelStore: ViewModelStore = ViewModelStore()

    override val defaultViewModelProviderFactory: ViewModelProvider.Factory =
        object : ViewModelProvider.Factory {
            @Suppress("UNCHECKED_CAST")
            override fun <T : ViewModel> create(
                modelClass: Class<T>,
                extras: CreationExtras,
            ): T =
                if (modelClass == QuickActionsViewModel::class.java) {
                    quickActions as T
                } else {
                    mockkClass(modelClass.kotlin, relaxed = true)
                }
        }
}
