package com.yt.player.state

data class EnhancedPlayerState(
    val currentVideoId: String? = null,
    val isPlaying: Boolean = false,
    val playWhenReady: Boolean = false,
    val isBuffering: Boolean = false,
    val isPrepared: Boolean = false,
    val hasEnded: Boolean = false,
    val currentQuality: Int = 0,
    val effectiveQuality: Int = 0,
    val currentQualityKey: String? = null,
    val currentAudioTrack: Int = 0,
    val sourceVideoAspectRatio: Float? = null,
    val availableQualities: List<QualityOption> = emptyList(),
    val availableAudioTracks: List<AudioTrackOption> = emptyList(),
    val availableSubtitles: List<SubtitleOption> = emptyList(),
    val error: String? = null,
    val recoveryAttempted: Boolean = false,
    val playbackSpeed: Float = 1.0f,
    val isSkipSilenceEnabled: Boolean = false,
    val isStableVolumeEnabled: Boolean = false,
    val bufferedPercentage: Float = 0f,
    val hasNext: Boolean = false,
    val hasPrevious: Boolean = false,
    val queueTitle: String? = null,
    val queueSize: Int = 0,
    val isQueueLooping: Boolean = false,
    val isQueueShuffled: Boolean = false,
    val isLooping: Boolean = false,
    val isLive: Boolean = false,
    val isAtLiveEdge: Boolean = false,
    val liveDurationMs: Long = 0L,
)

// video quality option for the quality selector.
data class QualityOption(
    val height: Int,
    val label: String,
    val bitrate: Long,
    val codecKey: String = "",
    val streamKey: String? = null,
)

// audio track option for the audio selector.
data class AudioTrackOption(
    val index: Int,
    val label: String,
    val language: String,
    val bitrate: Long,
)

// subtitle option for the subtitle selector.
data class SubtitleOption(
    val url: String,
    val language: String,
    val label: String,
    val isAutoGenerated: Boolean,
    val isTranslated: Boolean = false,
)
