package com.yt.ui.components.music.section

enum class HomeSectionType {
    DAILY_DISCOVER,
    QUICK_PICKS,
    FROM_COMMUNITY,
    RECOMMENDED,
    SIMILAR_TO,
    LIVE_PERFORMANCES,
    MUSIC_VIDEOS_FOR_YOU,
    MUSIC_VIDEOS,
    GENRES,
    DYNAMIC_HOME,
    TOP_ALBUMS,
    FAVORITE_ARTIST_ALBUMS,
    NEW_RELEASES,
    CHARTS,
    POPULAR_ARTISTS,
    MIXED_FOR_YOU,
    MOODS_AND_GENRES,
}
